//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoKevin.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/IniciarSesionDesdeServicio", ReplyAction="http://tempuri.org/IService2/IniciarSesionDesdeServicioResponse")]
        bool IniciarSesionDesdeServicio(string password, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/IniciarSesionDesdeServicio", ReplyAction="http://tempuri.org/IService2/IniciarSesionDesdeServicioResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionDesdeServicioAsync(string password, string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : ProyectoKevin.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<ProyectoKevin.ServiceReference2.IService2>, ProyectoKevin.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesionDesdeServicio(string password, string correo) {
            return base.Channel.IniciarSesionDesdeServicio(password, correo);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionDesdeServicioAsync(string password, string correo) {
            return base.Channel.IniciarSesionDesdeServicioAsync(password, correo);
        }
    }
}
